name: face_attendance
description: Aplicación Flutter de asistencia con reconocimiento facial offline usando MobileFaceNet.tflite
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.5+9
  google_mlkit_face_detection: ^0.11.0
  google_mlkit_commons: ^0.6.1
  tflite_flutter: ^0.10.4
  image: ^4.2.0
  path_provider: ^2.1.2
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  collection: ^1.18.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilefacenet.tflite


